version: '3.9'

services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile.dev
      target: production
    networks:
      - frontend
      - backend
    environment:
      - PORT=${PORT}
    env_file:
      - .env
    volumes:
      # this is a workaround to prevent host node_modules from accidently getting mounted in container
      - notused:/usr/src/app/node_modules
      - .env:/usr/src/app/.env
    depends_on:
      - redis
    container_name: yuki_server

  redis:
    container_name: yuki_redis
    networks:
        - backend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  notused: